jira:
  image: flaviojmendes/atlassian-jira:6.3.3
  restart: always
  links:
    - database
  volumes:
    - home:/opt/jira-home
  ports:
    - 8080:8080

database:
  image: postgres:9.4
  restart: always
  volumes:
    - data:/var/lib/postgresql/data
    - setup-jira-db.sh:/docker-entrypoint-initdb.d/setup-jira-db.sh
